'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),K=require('../dist/core.js'),S=require('../dist/profile.js'),D=require('../dist/scene-data.js');let count=0;
const test=(n,f)=>{f();count++;console.log('PASS '+n);},ids=Object.keys(K.mowerProfiles);
const memory=raw=>{let data=JSON.stringify(raw||{});return {getItem:()=>data,setItem:(k,v)=>{assert.equal(k,'klippekaos-p05');data=v;}};};
const result=stage=>({garden:'career'+stage,mode:'normal',completed:true,failed:false,score:1000,coverage:1,time:100,overlap:0,initials:'ABC'});
function run(g,t){for(let i=0;i<Math.round(t*120);i++)g.step(1/120);}

test('Unlock requirements are data-driven and follow the approved six-machine mapping',()=>{assert.deepEqual(Object.values(K.mowerProfiles).map(p=>p.unlockAfterCareerLevel),[0,1,2,3,4,5]);const M=require('../dist/render/mower.js');assert(M.SPRITES[ids[4]].src.endsWith('mower-05-zero-turn-yellow.png'));assert(M.SPRITES[ids[5]].src.endsWith('mower-04-ride-tractor-yellow.png'));});
test('A fresh profile can use only the starter and rejects locked or unknown choices',()=>{const p=S.load(memory());assert.deepEqual(p.unlockedMowers,[ids[0]]);assert.equal(p.selectedMower,ids[0]);assert(!S.selectMower(p,ids[5]));assert(!S.selectMower(p,'unknown'));assert.equal(p.selectedMower,ids[0]);});
test('Career milestones unlock exactly one next machine and leave the current choice intact',()=>{const p=S.load(memory());for(let stage=1;stage<=5;stage++){assert.deepEqual(S.completeCareer(p,result(stage)),[ids[stage]]);assert.equal(p.unlockedMowers.length,stage+1);assert.equal(p.selectedMower,ids[0]);assert.equal(p.unlocked,Math.min(5,stage+1));}});
test('Replay, failure, timed games, test gardens and inaccessible stages cannot award a machine',()=>{const p=S.load(memory());for(const r of [{...result(1),failed:true},{...result(1),completed:false},{...result(1),mode:'timed'},{...result(1),garden:'garden1'},result(3)])assert.deepEqual(S.completeCareer(p,r),[]);S.completeCareer(p,result(1));assert.deepEqual(S.completeCareer(p,result(1)),[]);});
test('Chosen mower persists across sessions and earlier unlocked machines remain selectable',()=>{const store=memory(),p=S.load(store);S.completeCareer(p,result(1));assert(S.selectMower(p,ids[1]));assert(S.save(store,p.book,p.unlocked,p));const q=S.load(store);assert.equal(q.selectedMower,ids[1]);assert(S.selectMower(q,ids[0]));assert.equal(q.selectedMower,ids[0]);});
test('Completion is persisted before initials, so an unlock cannot be repeated after reload',()=>{const store=memory(),p=S.load(store);S.completeCareer(p,result(1));S.save(store,{},p.unlocked,p);assert.deepEqual(S.completeCareer(S.load(store),result(1)),[]);});
test('Legacy profile migration preserves scores and progress while deriving unlocked machines',()=>{const book=K.recordRun({},result(2)),store=memory({book,unlocked:3}),p=S.load(store);assert.equal(p.unlocked,3);assert.equal(p.selectedMower,ids[0]);assert.deepEqual(p.unlockedMowers,ids.slice(0,3));assert.deepEqual(p.book,book);S.save(store,p.book,p.unlocked,p);assert.deepEqual(S.load(store).book,book);});
test('Legacy final-stage unlock requires evidence of completion, not merely access to level five',()=>{assert.deepEqual(S.load(memory({unlocked:5})).unlockedMowers,ids.slice(0,5));const p=S.load(memory({unlocked:5,book:K.recordRun({},result(5))}));assert.deepEqual(p.unlockedMowers,ids);assert.deepEqual(S.completeCareer(p,result(5)),[]);});
test('Malformed mower fields fall back safely without losing valid career progress',()=>{for(const raw of [{selectedMower:ids[5],unlockedMowers:[]},{selectedMower:'bad',unlockedMowers:['bad']},{selectedMower:4,unlockedMowers:{}}]){const p=S.load(memory({...raw,unlocked:2}));assert.equal(p.selectedMower,ids[0]);assert.deepEqual(p.unlockedMowers,ids.slice(0,2));}assert(!S.load({getItem(){throw Error();}}).ok);});
test('Every career level has explicit cat settings while wasps stay exclusive to level five',()=>{const expected=[[30,28,2],[25,22,2],[18,17,3],[18,16,3],[18,13.5,4]];for(let i=1;i<=5;i++){const g=new K.Game('normal','career'+i);assert(g.catSettings.enabled&&g.mechanics.cat);assert.deepEqual([g.catSettings.first,g.catSettings.cooldown,g.catSettings.maxPasses],expected[i-1]);assert.equal(g.waspNests.length>0,i===5);}});
test('All five cat schedules respect their first warning, cooldown and maximum passes',()=>{for(let stage=1;stage<=5;stage++){const g=new K.Game('normal','career'+stage,undefined,{catRoute:'left-right'});g.started=true;g.x=100;g.y=500;const warnings=[],exits=[];for(let i=0;i<190*20;i++){g.time=i/20;const events=[];g.updateCat(.05,events);if(events.includes('cat-warning'))warnings.push(g.time);if(events.includes('cat-gone'))exits.push(g.time);}assert.equal(exits.length,g.catSettings.maxPasses);assert.equal(warnings.length,exits.length);assert(Math.abs(warnings[0]-(g.catSettings.first-1.5))<.051);for(let i=1;i<warnings.length;i++)assert(Math.abs(warnings[i]-exits[i-1]-g.catSettings.cooldown)<.051);assert(!g.cat.active);g.reset();assert.equal(g.catPasses,0);}});
test('Level one still warns and loses on cat contact with no safety stop or wasps',()=>{const g=new K.Game('normal','career1',undefined,{catRoute:'left-right'});g.started=true;g.time=28.5;const events=[];g.updateCat(0,events);assert.deepEqual(events,['cat-warning']);g.x=20;g.y=280;g.time=30.25;run(g,.2);assert(g.done);assert.equal(g.reason,'cat-collision');assert.equal(g.waspSpawns.length,0);});
test('Level five queues physical nest crossings behind cats without concurrent dangers',()=>{const g=new K.Game('normal','career5',undefined,{seed:42,catRoute:'left-right'});g.started=true;g.x=100;g.y=500;g.time=16.5;g.updateCat(0,[]);const n=g.waspNests[0];g.encounterWasps(n.x-1,n.y,n.x,n.y);assert.equal(n.state,'queued');for(let i=0;i<130*120;i++){g.step(1/120);assert(!(g.nest.active&&(g.cat.active||(g.cat.warned&&!g.cat.finished))));}assert.equal(g.waspSpawns.length,1);assert.equal(g.catPasses,4);});
test('Stone bed descriptors preserve every collider and use a bounded centered visual',()=>{for(const l of [...Object.values(K.levels),...Object.values(K.careerLevels)]){const before=JSON.stringify(l),g=new K.Game('normal',l.id),coverage=g.total;const d=D.forLevel(l);for(const v of d.obstacleVisuals){const o=l.obstacles[v.colliderIndex];if(o.type!=='rect')continue;assert.equal(v.sprite,'flower-bed-stone-01');assert(v.solidBed);assert(!K.legal(o.x+o.w/2,o.y+o.h/2,l.id));assert(K.legal(o.x-14,o.y+o.h/2,l.id));}assert.equal(JSON.stringify(l),before);assert.equal(g.total,coverage);}});
test('Solid flowerbed loading fallback has no prototype flower grid and uses the new PNG',()=>{const images=[],draws=[],rects=[];const ctx=new Proxy({drawImage(...args){draws.push(args);},fillRect(...args){rects.push(args);}},{get:(o,k)=>o[k]??(()=>{})});const sandbox={Image:class{constructor(){images.push(this);}naturalWidth=1254;naturalHeight=1254;}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('dist/render/assets.js','utf8'),sandbox);const d={asset:'flowerbed',sprite:'flower-bed-stone-01',solidBed:true,x:0,y:0,w:124,h:74};sandbox.KlippeAssets.draw(ctx,d);assert.equal(rects.length,0);images[0].onload();sandbox.KlippeAssets.draw(ctx,d);assert.equal(draws.length,1);assert(draws[0][0].src.endsWith('flower-bed-stone-01.png'));assert.equal(rects.length,0);});
test('Migration keeps original dates and best time/overlap outside the current top five',()=>{const book=K.recordRun({},result(1));book['career1:normal'].time=45;book['career1:normal'].overlap=0;book['career1:normal'].runs[0].overlap=.2;book['career1:normal'].runs[0].date='2025-01-01T12:00:00.000Z';const store=memory({book,unlocked:2}),p=S.load(store);assert.deepEqual(p.book,book);S.save(store,p.book,p.unlocked,p);assert.deepEqual(S.load(store).book,book);});
console.log(count+' PASS');
