
'use strict';
const assert=require('node:assert/strict'),M=require('../dist/mouse-input.js'),K=require('../dist/core.js'),V=require('../dist/render/viewport.js');
let count=0;function test(n,f){f();count++;console.log('PASS '+n);}
const ev=(o={})=>({pointerType:'mouse',pointerId:1,button:2,buttons:2,clientX:200,clientY:400,preventDefault(){this.prevented=true;},...o});
function surface(){return {listeners:{},captured:null,addEventListener(n,f){(this.listeners[n]??=[]).push(f);},emit(n,e=ev()){for(const f of this.listeners[n]||[])f(e);return e;},setPointerCapture(id){this.captured=id;},hasPointerCapture(id){return this.captured===id;},releasePointerCapture(){this.captured=null;}};}
function setup(){const c=surface(),host=surface(),m=new M.MouseInput(),state={enabled:true};M.bind(c,m,{enabled:()=>state.enabled,onStart(){},window:host});return {c,host,m,state};}
test('Right pointerdown gives negative normalized throttle',()=>{const {c,m}=setup();c.emit('pointerdown');assert.equal(m.read({x:200,y:200,angle:0},V.fit(900,580),{left:0,top:0}).throttle,-1);});
test('Right release, cancel, lost capture, missing buttons and blur clear throttle',()=>{const outside=setup();outside.c.emit('pointerdown');outside.c.emit('pointermove',ev({button:-1,clientX:2000,clientY:-200}));outside.host.emit('pointerup',ev({buttons:0}));assert(!outside.m.active);for(const name of ['pointerup','pointercancel','lostpointercapture','mouseup','blur','pointermove']){const {c,host,m}=setup();c.emit('pointerdown');(name==='blur'||name==='mouseup'?host:c).emit(name,ev({buttons:0,button:name==='pointermove'?-1:2}));assert(!m.active,name);assert.equal(m.read({},null,null).throttle,0);}});
test('Straight rear target gives reverse with zero steering at every heading',()=>{for(const angle of [-3,-1,0,1,3]){const g={x:300,y:300,angle},r=M.command(g,{x:300-100*Math.cos(angle),y:300-100*Math.sin(angle)},-1);assert.equal(r.throttle,-1);assert(Math.abs(r.steering)<1e-9);}});
function driveRear(side){const g=new K.Game('normal','career1');g.x=350;g.y=400;g.angle=0;const target={x:200,y:400+side*85},initial=Math.hypot(target.x-g.x,target.y-g.y),first=M.command(g,target,-1);for(let i=0;i<300;i++)g.step(1/120,M.command(g,target,-1));assert(Math.hypot(target.x-g.x,target.y-g.y)<initial*.5);assert.equal(g.collisions,0);assert((g.y-400)*side>25);return first;}
test('Rear-left target moves rear left through actual reverse physics',()=>{assert(driveRear(-1).steering<0);});
test('Rear-right target moves rear right through actual reverse physics',()=>{assert(driveRear(1).steering>0);});
test('Left press takes over held right including chorded pointermove',()=>{const {c,host,m}=setup();c.emit('pointerdown');c.emit('pointermove',ev({button:0,buttons:3}));assert.equal(m.button,0);host.emit('mouseup',ev({button:2,buttons:1}));assert(m.active);host.emit('mouseup',ev({button:0,buttons:0}));assert(!m.active);});
test('Right press takes over held left and releasing active button never resumes old throttle',()=>{const {c,host,m}=setup();c.emit('pointerdown',ev({button:0,buttons:1}));c.emit('pointermove',ev({button:2,buttons:3}));assert.equal(m.button,2);host.emit('mouseup',ev({button:2,buttons:1}));assert(!m.active);c.emit('pointermove',ev({button:-1,buttons:1}));assert(!m.active);});
test('Context menu is suppressed only on enabled scene, never host or HUD',()=>{const {c,host,state}=setup(),hud=surface();assert(c.emit('contextmenu').prevented);assert(!host.emit('contextmenu').prevented);assert(!hud.emit('contextmenu').prevented);state.enabled=false;assert(!c.emit('contextmenu').prevented);c.emit('pointerdown');assert.equal(c.captured,null);});
test('Touch and keyboard/gamepad arbitration remain independent of reverse mouse',()=>{const {c,m}=setup();c.emit('pointerdown',ev({pointerType:'touch'}));assert(!m.active);const zero={throttle:0,steering:0},keys={throttle:1,steering:-1},touch={throttle:-1,steering:.4};assert.equal(M.arbitrate(false,zero,keys,touch,zero).throttle,1);assert.equal(M.arbitrate(false,zero,zero,touch,zero).steering,.4);assert.equal(M.arbitrate(false,zero,zero,zero,keys).steering,-1);});
test('Reverse close target is stronger, finite and bounded; release coasts with existing drag',()=>{const g=new K.Game('normal','career1');g.x=700;g.y=290;g.angle=0;const near=M.command(g,{x:670,y:270},-1),far=M.command(g,{x:400,y:90},-1);assert(Math.abs(near.steering)>Math.abs(far.steering));assert.equal(M.command(g,g,-1).steering,0);for(let i=0;i<60;i++)g.step(1/120,M.command(g,{x:500,y:290},-1));const speed=g.speed;assert(speed<0);g.step(1/120,{});assert(g.speed>speed&&g.speed<0);for(let i=0;i<120;i++)g.step(1/120,{});assert.equal(g.speed,0);});
console.log(count+' PASS');
