
'use strict';
const assert=require('node:assert/strict'),M=require('../dist/mouse-input.js');
let n=0;function test(name,fn){fn();n++;console.log('PASS '+name);}
function surface(){return {listeners:{},capture:null,addEventListener(n,f){(this.listeners[n]??=[]).push(f);},emit(type,extra={}){const e={type,pointerType:'mouse',pointerId:1,button:2,buttons:2,clientX:100,clientY:200,preventDefault(){this.prevented=true;},stopPropagation(){this.stopped=true;},...extra};for(const f of this.listeners[type]||[])f(e);return e;},setPointerCapture(id){this.capture=id;},hasPointerCapture(id){return this.capture===id;},releasePointerCapture(){this.capture=null;}};}
function setup(){const canvas=surface(),host=surface(),mouse=new M.MouseInput(),state={enabled:true},clear=M.bind(canvas,mouse,{window:host,enabled:()=>state.enabled,onStart(){}});return {canvas,host,mouse,state,clear};}
test('Active scene cancels contextmenu and right down without cancelling held reverse',()=>{const {canvas,mouse}=setup();assert(canvas.emit('pointerdown').prevented);assert.equal(mouse.button,2);assert(canvas.emit('contextmenu').prevented);assert(mouse.active);});
test('Right release outside retains cancellation for only that gesture tail',()=>{const {canvas,host,mouse}=setup();canvas.emit('pointerdown');canvas.emit('pointermove',{button:-1,clientX:3000,buttons:2});host.emit('pointerup',{buttons:0});assert(!mouse.active);assert(host.emit('contextmenu',{buttons:0}).prevented);assert(host.emit('auxclick',{buttons:0}).prevented);assert(!mouse.active);host.emit('pointerdown');assert(!host.emit('contextmenu').prevented);});
test('No global context/aux suppression; inactive scene and middle button keep defaults',()=>{const {canvas,host,state}=setup();assert(!host.emit('contextmenu').prevented);assert(!host.emit('auxclick').prevented);assert(!canvas.emit('auxclick',{button:1}).prevented);state.enabled=false;for(const t of ['contextmenu','auxclick','dragstart','selectstart'])assert(!canvas.emit(t).prevented);canvas.emit('pointerdown');assert.equal(canvas.capture,null);});
test('Native dragging and selection on active canvas are stopped and clear reverse',()=>{for(const name of ['dragstart','selectstart']){const {canvas,mouse}=setup();canvas.emit('pointerdown');assert(canvas.emit(name).prevented);assert(!mouse.active);}});
test('Context menu on button down retains control; release auxclick clears missing-up state',()=>{const {canvas,mouse}=setup();canvas.emit('pointerdown');canvas.emit('contextmenu',{buttons:2});assert(mouse.active);assert(canvas.emit('auxclick',{buttons:0}).prevented);assert(!mouse.active);});
test('Cancel, lost capture, blur and pause cleanup stop reverse, late context menu cannot restart it',()=>{for(const action of ['pointercancel','lostpointercapture','blur','pause']){const {canvas,host,mouse,state,clear}=setup();canvas.emit('pointerdown');if(action==='pause'){state.enabled=false;clear();}else (action==='blur'?host:canvas).emit(action);assert(!mouse.active);assert(host.emit('contextmenu',{buttons:0}).prevented);assert(!mouse.active);host.emit('pointerdown');state.enabled=false;assert(!canvas.emit('contextmenu').prevented);}});
console.log(n+' PASS');
