
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),K=require('../dist/core.js'),M=require('../dist/render/mower.js');
let n=0;function test(name,fn){fn();n++;console.log('PASS '+name);}
const close=(a,b)=>assert(Math.abs(a-b)<1e-9);
test('Deck anchor remains exactly at gameplay position at every heading and source size',()=>{for(const angle of [0,Math.PI/2,Math.PI,-Math.PI/2,1.7])for(const scale of [.05,.105,.2]){const spec={...M.SPRITES[M.ACTIVE],scale},g={x:234,y:345,angle},p=M.spritePoint(g,spec.anchor,spec);close(p.x,g.x);close(p.y,g.y);}});
test('Native downward front becomes chassis forward and person remains behind at every heading',()=>{const spec=M.SPRITES[M.ACTIVE];for(const angle of [0,.3,Math.PI/2,Math.PI,-Math.PI/2]){const g={x:200,y:200,angle},front=M.spritePoint(g,{x:625,y:1050}),person=M.spritePoint(g,{x:625,y:260});assert((front.x-g.x)*Math.cos(angle)+(front.y-g.y)*Math.sin(angle)>0);assert((person.x-g.x)*Math.cos(angle)+(person.y-g.y)*Math.sin(angle)<-60);}});
function runtime(){const requests=[],ctx=new Proxy({draws:[],drawImage(...a){this.draws.push(a);}},{get:(o,k)=>o[k]??(()=>{})});const sandbox={KlippeAssets:{rounded(){},circle(){}},Image:class{constructor(){requests.push(this);}}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(require.resolve('../dist/render/mower.js'),'utf8'),sandbox);return {sandbox,requests,ctx,m:sandbox.KlippeMower};}
test('Missing, failed or wrong-sized PNG uses existing Canvas fallback without throwing',()=>{const {m,requests,ctx}=runtime(),g=new K.Game('normal','career1');m.draw(ctx,g);assert.equal(ctx.draws.length,0);requests[0].onerror();m.draw(ctx,g);assert.equal(ctx.draws.length,0);requests[0].naturalWidth=99;requests[0].naturalHeight=99;requests[0].onload();m.draw(ctx,g);assert.equal(ctx.draws.length,0);});
test('Loaded PNG uses explicit dimensions once, never changes game and preserves fallback sprite contract',()=>{const {m,requests,ctx}=runtime(),g=new K.Game('normal','career1'),before=JSON.stringify(g),spec=m.SPRITES[m.ACTIVE];requests[0].naturalWidth=1254;requests[0].naturalHeight=1254;requests[0].onload();m.draw(ctx,g);assert.equal(requests.length,1);assert.equal(ctx.draws.length,1);close(ctx.draws[0][1],-625*.105);close(ctx.draws[0][2],-890*.105);close(ctx.draws[0][3],1254*.105);assert.equal(JSON.stringify(g),before);assert.equal(K.P.body,14);assert.equal(K.P.deck,23);});
test('Foreground fades for person behind mower while collision and solid trunk remain untouched',()=>{const {sandbox,m,requests}=runtime();requests[0].naturalWidth=1254;requests[0].naturalHeight=1254;requests[0].onload();vm.runInContext(fs.readFileSync(require.resolve('../dist/render/scene.js'),'utf8'),sandbox);const game={x:200,y:200,angle:0,cat:{active:false},nest:{active:false}},before=JSON.stringify(game),person=m.spritePoint(game,{x:625,y:260}),d={x:person.x,y:person.y,w:12,h:12};close(sandbox.KlippeScene.foregroundAlpha(d,game),.35);requests[0].onerror();assert(sandbox.KlippeScene.foregroundAlpha(d,game)>.9);assert.equal(JSON.stringify(game),before);});
test('Source PNG has alpha and dimensions matching metadata',()=>{const s=M.SPRITES[M.ACTIVE],b=fs.readFileSync('public/art/mowers/'+s.id+'.png');assert.equal(b.readUInt32BE(16),s.width);assert.equal(b.readUInt32BE(20),s.height);assert.equal(b[25],6);});
console.log(n+' PASS');
