'use strict';
const assert=require('node:assert/strict'),K=require('../dist/core.js'),D=require('../dist/scene-data.js'),A=require('../dist/render/assets.js'),S=require('../dist/render/scene.js');let count=0;
function test(name,fn){fn();console.log('PASS '+name);count++;}
const mock=()=>new Proxy({},{get:(o,k)=>k in o?o[k]:(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
function withCanvas(fn){const old=global.document;let created=0;global.document={createElement:()=>{created++;return {width:0,height:0,getContext:mock};}};try{fn(()=>created);}finally{global.document=old;}}
test('Every kit asset and three foliage variants render deterministically without consuming gameplay RNG',()=>{for(const asset of A.KIT)for(let variant=0;variant<3;variant++){const traces=[];for(let n=0;n<2;n++){const calls=[],c=new Proxy({},{get:(o,k)=>k in o?o[k]:(...args)=>calls.push([k,...args]),set:(o,k,v)=>(o[k]=v,true)});A.draw(c,{asset,variant,x:0,y:0,w:100,h:80});traces.push(calls);}assert.deepEqual(traces[0],traces[1]);assert(traces[0].some(c=>c[0]==='fill'));}});
test('Career profiles use only kit assets, cover the full kit, and remain independent copies',()=>{const used=new Set();for(const level of Object.values(K.careerLevels)){const d=D.forLevel(level);for(const p of [...d.decor,...d.obstacleVisuals]){assert(A.KIT.includes(p.asset));used.add(p.asset);}const before=JSON.stringify(D.forLevel(level));d.decor[0].anchor[0]=99;assert.equal(JSON.stringify(D.forLevel(level)),before);}assert.equal(used.size,A.KIT.length);});
test('Every existing solid tree has a larger visual crown with legally mowable space underneath',()=>{for(const level of Object.values(K.careerLevels)){const d=D.forLevel(level);for(const v of d.obstacleVisuals.filter(v=>v.layer==='foreground')){const o=level.obstacles[v.colliderIndex],x=o.x+o.r+K.P.body+1;assert(o.r*v.canopyFactor>o.r+K.P.body+1);assert(K.legal(x,o.y,level.id));assert(K.mowable(x,o.y,level.id));assert.equal(S.foregroundAlpha({...v,x:o.x,y:o.y,w:o.r*2*v.canopyFactor,h:o.r*2*v.canopyFactor},{x,y:o.y,cat:{active:false},nest:{active:false}}),.35);}}});
test('Mower, Blender and wasps independently fade the complete overhanging crown with a continuous ramp',()=>{const d={x:100,y:100,w:112,h:112},base={x:600,y:500,cat:{active:false},nest:{active:false}};for(const type of ['mower','cat','nest']){let previous=.35;for(let dx=0;dx<=180;dx+=.5){const actor={active:true,x:100+dx,y:100};const g=type==='mower'?{...base,...actor}:{...base,[type]:actor};const a=S.foregroundAlpha(d,g);assert(a>=previous-1e-9&&a-previous<.017);previous=a;}assert.equal(previous,1);}});
test('Foreground uses bounded cached sprites with no per-frame canvases or lawn clipping',()=>withCanvas(created=>{for(const level of Object.values(K.careerLevels)){const game=new K.Game('normal',level.id),s=S.create(game,K.P);s.reset();const initial=created(),before=JSON.stringify(game),c=mock();let clips=0;c.clip=()=>clips++;for(let i=0;i<60;i++)s.foreground(c);assert.equal(clips,0);assert.equal(created(),initial);assert(s.diagnostics().foregroundPixels<1000000);assert.equal(JSON.stringify(game),before);}}));
test('Solid trunk rendering stays separate from fading foliage and scene reset is bounded',()=>withCanvas(()=>{const g=new K.Game('normal','career3'),s=S.create(g,K.P),c=mock();s.reset();const first=s.diagnostics();for(let i=0;i<3;i++)s.reset();assert.deepEqual(s.diagnostics(),first);const draw=A.draw,calls=[];A.draw=(ctx,d)=>calls.push({asset:d.asset,alpha:ctx.globalAlpha});try{c.globalAlpha=1;s.obstacles(c);assert(calls.some(x=>x.asset==='trunk'&&x.alpha===1));}finally{A.draw=draw;}}));
console.log(count+' PASS');
