'use strict';
const assert=require('node:assert/strict'),K=require('../dist/core.js'),S=require('../dist/render/stripes.js'),C=require('../dist/render/particles.js'),V=require('../dist/render/viewport.js');require('../dist/render/assets.js');const Lawn=require('../dist/render/lawn.js'),M=require('../dist/render/mower.js');
let count=0;function test(name,fn){fn();count++;console.log('PASS '+name);}
const mock=()=>new Proxy({},{get:(o,k)=>k in o?o[k]:(()=>{}),set:(o,k,v)=>(o[k]=v,true)});
function canvasTest(fn){const before=global.document;global.document={createElement:()=>({width:0,height:0,getContext:()=>mock()})};try{fn();}finally{global.document=before;}}
test('Direction is first-cut per six-unit visual cell and only supplied fresh cells change it',()=>{const s=new S.DirectionBuffer(900,580);assert.equal(s.directions.length,14550);s.record([0],.7,450,2);assert(Math.abs(s.directions[0]-.7)<1e-6);s.record([1],2,450,2);assert(Math.abs(s.directions[0]-.7)<1e-6);const before=Buffer.from(s.directions.buffer).toString('hex');s.record([],1,450,2);assert.equal(Buffer.from(s.directions.buffer).toString('hex'),before);s.record([3],2,450,2);assert.equal(s.directions[1],2);});
test('Reflectance varies continuously by local direction, with opposite passes reflecting differently',()=>{assert(Math.abs(S.reflectance(0)+S.reflectance(Math.PI))<1e-9);assert.notEqual(S.style(.2),S.style(.7));assert(Math.abs(S.reflectance(.4001)-S.reflectance(.4))<.001);});
test('Visual reset removes all stored directions',()=>{const s=new S.DirectionBuffer(900,580);s.record([0,5000],1,450,2);s.reset();assert(s.directions.every(Number.isNaN));});
test('Stripe updates leave mask, overlap, score and flower state untouched',()=>{const g=new K.Game('normal','career4'),s=new S.DirectionBuffer(900,580);for(let i=0;i<180;i++){const e=g.step(1/120,{throttle:1});const before=JSON.stringify(g);s.record(e.cells,g.angle,g.nx,K.P.cell);assert.equal(JSON.stringify(g),before);}});
test('Overlapping visual passes do not accumulate direction or repaint old logical cells',()=>{const g=new K.Game('normal','career1'),s=new S.DirectionBuffer(900,580);g.recentCells=[];g.mow(150,400);s.record(g.recentCells,0,g.nx,K.P.cell);const before=Buffer.from(s.directions.buffer).toString('hex');g.recentCells=[];g.travel+=500;const fresh=g.mow(150,400);assert.equal(fresh,0);assert(g.repeat>0);assert.equal(s.record(g.recentCells,Math.PI,g.nx,K.P.cell).length,0);assert.equal(Buffer.from(s.directions.buffer).toString('hex'),before);});
test('Resize upgrades cached texture quality without resetting direction or model state',()=>canvasTest(()=>{const g=new K.Game('normal','career1'),r=Lawn.create(g,K.P);r.reset();const e=g.step(1/120,{throttle:1});r.cut(e);const directions=Buffer.from(r.stripes.directions.buffer).toString('hex'),before=JSON.stringify(g),builds=r.diagnostics().builds;assert(r.resize(1,1.5));assert.equal(r.diagnostics().ratio,1.5);assert.equal(Buffer.from(r.stripes.directions.buffer).toString('hex'),directions);assert.equal(JSON.stringify(g),before);for(let i=0;i<100;i++)assert(!r.resize(.8,1));assert.equal(r.diagnostics().builds,builds+1);r.resize(2,3);assert.equal(r.diagnostics().ratio,2);assert.equal(r.diagnostics().cachePixels,5220000);r.reset();assert(r.stripes.directions.every(Number.isNaN));}));
test('Heavy grass and flowers can be rendered and rebuilt without changing physics',()=>canvasTest(()=>{for(const id of ['career2','career4']){const g=new K.Game('normal',id),before=JSON.stringify(g),r=Lawn.create(g,K.P);r.reset({scale:1,dpr:2});r.draw(mock());r.resize(3,2);assert.equal(JSON.stringify(g),before);}}));
test('Mower art and replacement sprite use visual dimensions only and never mutate a mower',()=>{const g=new K.Game('normal','career1'),before=JSON.stringify(g);M.draw(mock(),g,{settings:{reduced:false},last:400,cutLevel:1});M.draw(mock(),g,{sprite:{width:4096,height:4096}});assert.equal(JSON.stringify(g),before);assert.deepEqual(M.BOUNDS,{x:-24,y:-24,w:48,h:48});assert.equal(K.P.body,14);assert.equal(K.P.deck,23);});
test('Fresh grass emits bounded short-lived particles, overlap and idle emit none',()=>{const s=new C.System(),g={angle:0,heavyLoad:0};for(let i=0;i<120;i++){s.emit({moved:true,fresh:11,x:i,y:0},g);s.update(1/120);}assert(s.items.length>=30&&s.items.length<=80);const n=s.items.length;s.emit({moved:true,fresh:0,x:0,y:0},g);s.emit({moved:false,fresh:100,x:0,y:0},g);assert.equal(s.items.length,n);s.update(1);assert.equal(s.items.length,0);});
test('Mobile and reduced motion restrict clippings; reset is deterministic',()=>{const s=new C.System(),g={angle:1,heavyLoad:1};for(let i=0;i<100;i++)s.emit({moved:true,fresh:30,x:0,y:0},g,{mobile:true});assert(s.items.length<=32);s.emit({moved:true,fresh:30,x:0,y:0},g,{reduced:true});assert.equal(s.items.length,0);s.emit({moved:true,fresh:30,x:0,y:0},g);const first=JSON.stringify(s.items);s.clear();s.emit({moved:true,fresh:30,x:0,y:0},g);assert.equal(JSON.stringify(s.items),first);s.update(.01,true);assert.equal(s.items.length,0);});
test('Particle system does not consume gameplay RNG or alter heavy-grass load',()=>{const g=new K.Game('normal','career2'),before=JSON.stringify(g),s=new C.System();s.emit({moved:true,fresh:100,x:g.x,y:g.y},g);s.update(.1);assert.equal(JSON.stringify(g),before);});
test('DPR 1, 1.25, 1.5 and 2 retain world coordinates and obey the canvas cap',()=>{for(const dpr of [1,1.25,1.5,2,3]){const v=V.fit(1440,900),c={width:0,height:0};V.begin(c,mock(),v,dpr);assert(c.width*c.height<=4000000);const screen=v.worldToScreen(234,123),world=v.screenToWorld(screen.x,screen.y);assert(Math.abs(world.x-234)<1e-8&&Math.abs(world.y-123)<1e-8);}});
console.log(count+' PASS');
