const assert=require('node:assert/strict');const {Game,P,levels,legal,mowable,recordRun,recordFlags,recordKey}=require('../dist/core.js');const tests=[];function test(n,f){f();tests.push(n);}function run(g,t,input={}){const events=[];for(let i=0;i<Math.round(t*120);i++){const e=g.step(1/120,input);if(e)events.push(...e.events);}return events;}function near(a,b,e=1e-6){assert(Math.abs(a-b)<e,`${a} vs ${b}`);}
test('Original shapes preserved; L-shaped void is non-mowable but drivable',()=>{assert(levels.garden1&&levels.garden2);assert(mowable(780,470));assert(!mowable(780,470,'garden2'));assert(legal(780,470,'garden2'));assert(mowable(460,470,'garden2'));assert(mowable(780,280,'garden2'));});
test('Lawn shape changes collision objects and coverage together',()=>{const g=new Game('normal','garden2');assert(!legal(380,390,g.garden));assert(!mowable(380,390,g.garden));assert(legal(630,370,g.garden));assert(g.total<new Game().total);});
test('Both coverage masks are fully reachable without crossing obstacles',()=>{for(const garden of ['garden1','garden2']){const g=new Game('normal',garden);for(let y=24;y<=554;y+=4)for(let x=28;x<=872;x+=4)if(legal(x,y,garden))g.mow(x,y);assert(g.coverage>=.995,`${garden}: ${g.coverage}`);console.log(garden+' reachable '+(g.coverage*100).toFixed(3)+'%');}});
test('Fresh-cell payload is unique and never re-shades an old patch',()=>{const g=new Game();const cells=[];for(let i=0;i<120;i++)cells.push(...g.step(1/120,{forward:true}).cells);assert.equal(cells.length,new Set(cells).size);assert.equal(cells.length,g.cut);const n=g.cut;run(g,.8);const e=g.step(1/120);assert.equal(e.cells.length,0);assert(g.cut>=n);});
test('Damage warns before it occurs; short stops remain safe',()=>{const g=new Game();run(g,.4,{forward:true});run(g,.4);const events=run(g,1.9);assert.equal(g.damage.length,0);assert(events.includes('damage-warning'));run(g,2);assert.equal(g.damage.length,1);assert.equal(g.result().breakdown.damage,60);run(g,7);assert.equal(g.damage.length,1);});
test('Moving on clears warning and prevents damage',()=>{const g=new Game();run(g,.2,{forward:true});run(g,2);assert.equal(g.damage.length,0);run(g,1,{forward:true});assert.equal(g.damage.length,0);assert.equal(g.idleTime,0);});
test('No damage before start, off lawn or while blocked',()=>{let g=new Game();run(g,8);assert.equal(g.damage.length,0);g.x=35;g.y=450;run(g,.1,{forward:true});run(g,6);assert.equal(g.damage.length,0);g=new Game();g.x=302;g.y=280;run(g,9,{forward:true});assert.equal(g.damage.length,0);});
test('Positive find stays hidden before mowing and grants one small refill',()=>{const g=new Game();g.x=g.find.x;g.y=g.find.y;g.energy.speed=.5;g.energy.turn=.7;run(g,.1);assert(!g.find.revealed);run(g,.1,{forward:true});assert(g.find.revealed&&g.find.collected);near(g.energy.speed,1.1);near(g.energy.turn,1.3);run(g,.1);near(g.energy.speed,1.1);});
test('Full boost stores preserve the revealed find until it can be collected',()=>{const g=new Game();g.x=g.find.x;g.y=g.find.y;g.energy.speed=3;g.energy.turn=3;run(g,.1,{forward:true});assert(g.find.revealed&&!g.find.collected);g.energy.speed=2.8;g.step(1/120);assert(g.find.collected);near(g.energy.speed,3);});
test('Cat warns, follows its fixed route and exits without steering assist',()=>{const g=new Game();g.started=true;g.x=100;g.y=450;g.time=16.4;const events=run(g,.3);assert(events.includes('cat-warning'));run(g,9);assert(g.cat.finished);near(g.cat.y,280);assert(!g.done);});
test('Approaching a cat preserves driving and boost before actual contact',()=>{const g=new Game();g.started=true;g.time=19;g.cat.x=360;g.cat.y=280;g.x=420;g.y=280;g.angle=Math.PI;g.speed=112;const energy=g.energy.speed;g.step(1/120,{forward:true,speedBoost:true});assert(!g.done);assert(g.speed>=112);assert(g.energy.speed<energy);assert.equal(g.damage.length,0);});
test('New score is exact and side events remain minor',()=>{const g=new Game();g.cut=g.total;g.time=150;g.collisions=100;g.damage=Array.from({length:10},()=>({x:1,y:1}));g.penalty=200;const r=g.result();assert.equal(r.breakdown.collisions,250);assert.equal(r.breakdown.damage,300);assert.equal(r.breakdown.wasps,200);assert.equal(r.score,r.breakdown.base-750);assert(r.score>8000);});
test('Records and flags are isolated by garden and mode; ties are not records',()=>{let book={};const g=new Game();g.cut=g.total;g.time=150;let r=g.result();assert(recordFlags(book,r).score);book=recordRun(book,r);assert(!recordFlags(book,r).score);assert(!recordFlags(book,r).time);assert(!recordFlags(book,r).overlap);g.time=140;r=g.result();assert(recordFlags(book,r).time);book=recordRun(book,r);assert.equal(book[recordKey(g)].time,140);g.reset('timed','garden2');g.time=60;r=g.result();book=recordRun(book,r);assert.equal(book['garden2:timed'].time,null);assert(!recordFlags({},r).time);assert.equal(book['garden1:normal'].runs.length,2);});
test('Mower capacity is configurable without changing base driving',()=>{const g=new Game('normal','garden1',{boostCapacity:5,boostStart:4});near(g.energy.speed,4);assert.equal(P.maxSpeed,112);g.reset();near(g.energy.speed,4);assert.equal(g.mower.boostCapacity,5);});
test('Reset clears damage, find and cat while preserving selected lawn',()=>{const g=new Game('normal','garden2');g.damage.push({x:1,y:1});g.find.revealed=true;g.cat.finished=true;g.reset();assert.equal(g.garden,'garden2');assert.equal(g.damage.length,0);assert(!g.find.revealed);assert(!g.cat.finished);});
console.log(tests.length+' PASS\n'+tests.join('\n'));
