const assert=require('node:assert/strict');const {Game,P,legal,mowable,recordRun,padInput}=require('../dist/core.js');const tests=[];function test(name,f){f();tests.push(name);}function run(g,seconds,input={}){for(let i=0;i<Math.round(seconds*120);i++)g.step(1/120,input);}function near(a,b,e=1e-6){assert(Math.abs(a-b)<e,`${a} vs ${b}`);}
test('Original basic driving parameters unchanged',()=>{assert.deepEqual([P.maxSpeed,P.reverseSpeed,P.acceleration,P.braking,P.drag,P.wheelbase,P.steerAngle],[112,53,155,290,195,32,.62]);});
test('Wheels cross all lawn edges; outer boundary remains solid',()=>{for(const [x,y,a] of [[62,450,Math.PI],[838,450,0],[100,54,-Math.PI/2],[100,526,Math.PI/2]]){const g=new Game();g.x=x;g.y=y;g.angle=a;run(g,.15,{forward:true});assert(legal(g.x,g.y));assert(Math.hypot(g.x-x,g.y-y)>1);run(g,2,{forward:true});assert(legal(g.x,g.y));assert(Math.abs(g.speed)<20);}});
test('Obstacle soil margin excluded; ordinary lawn still counts',()=>{assert(!mowable(331,208));assert(mowable(335,208));assert(!mowable(573,365));assert(mowable(569,365));assert(mowable(63,55));assert(!mowable(61,55));});
test('First pass no overlap; reversing gives overlap; stationary never adds overlap',()=>{const g=new Game();run(g,2,{forward:true});assert.equal(g.repeat,0);run(g,3,{back:true});assert(g.repeat>0);run(g,1);const r=g.repeat;run(g,5);assert.equal(g.repeat,r);});
test('Boost is held, independent, resumable, finite and does not recharge',()=>{const g=new Game();run(g,.5,{forward:true,speedBoost:true});near(g.energy.speed,2);near(g.energy.turn,2.5);assert(g.speed>P.maxSpeed);run(g,.5,{forward:true});near(g.energy.speed,2);run(g,.5,{forward:true,turnBoost:true});near(g.energy.speed,2);near(g.energy.turn,2);run(g,3,{forward:true,speedBoost:true});near(g.energy.speed,0);assert(g.energy.turn===2||Math.abs(g.energy.turn-2)<1e-6);run(g,1,{forward:true});near(g.energy.speed,0);assert(g.speed<=P.maxSpeed);});
test('Boost at rest does not waste energy or start timer',()=>{const g=new Game();run(g,3,{speedBoost:true,turnBoost:true});near(g.energy.speed,2.5);near(g.energy.turn,2.5);near(g.time,0);});
test('Maneuver boost changes curvature, not basic speed',()=>{const g=new Game(),h=new Game();run(g,.6,{forward:true,right:true});run(h,.6,{forward:true,right:true,turnBoost:true});near(g.speed,h.speed);near((h.angle+Math.PI/2)/(g.angle+Math.PI/2),1.85);});
test('Fixed pickups refill correct store once and obey capacity',()=>{const g=new Game();g.x=160;g.y=120;g.energy.speed=1;g.step(1/120);near(g.energy.speed,2.2);near(g.energy.turn,2.5);assert(g.pickups[0].taken);g.step(1/120);near(g.energy.speed,2.2);g.reset();g.x=160;g.y=120;g.energy.speed=3;g.step(1/120);assert(!g.pickups[0].taken);g.energy.speed=2.9;g.step(1/120);near(g.energy.speed,3);assert(g.pickups[0].taken);});
test('Timed mode starts on driving, ends at exactly 60 and freezes',()=>{const g=new Game('timed');run(g,5);near(g.remaining,60);run(g,1,{forward:true});run(g,65);assert(g.done);assert.equal(g.reason,'timeout');assert.equal(g.time,60);assert.equal(g.remaining,0);assert(g.result().coverage<1);let c=g.cut;run(g,1,{forward:true});assert.equal(g.cut,c);});
test('Both modes end on actual 99.5% coverage, shown as 100%',()=>{for(const mode of ['normal','timed']){const g=new Game(mode);g.cut=Math.ceil(g.total*.995)-1;g.step(1/120);assert(!g.done);g.cut++;g.step(1/120);assert(g.done);assert.equal(g.reason,'complete');assert.equal(g.result().coverage,1);}});
// Random arrival was intentionally replaced by a physical hidden-nest encounter.
test('Encountered hidden nest warns before pursuit and can sting only once per event',()=>{const g=new Game();g.started=true;const n=g.waspNests[0];g.x=n.x;g.y=n.y;g.encounterWasps(n.x-1,n.y,n.x,n.y);const e=[];assert(g.spawnWasps(e));assert(e.includes('wasps'));run(g,.5);assert.equal(g.penalty,0);run(g,1);assert(g.nest.caught);assert.equal(g.penalty,200);run(g,5);assert.equal(g.penalty,200);});

test('Nest can be escaped at base speed without boosts',()=>{const g=new Game();g.started=true;g.nest={x:300,y:450,originX:300,originY:450,revealed:true,active:true,age:0,caught:false};g.x=400;g.y=450;g.angle=0;run(g,2.8,{forward:true});run(g,1.7,{forward:true,left:true});assert(!g.nest.active);assert(!g.nest.caught);assert.equal(g.penalty,0);});
test('Collision counted on impact, not each frame of wall contact',()=>{const g=new Game();g.x=100;g.y=35;run(g,4,{forward:true});assert.equal(g.collisions,1);});
test('Score rewards coverage, lower overlap, faster time; penalties bounded',()=>{const g=new Game();g.cut=g.total;g.time=150;const base=g.result().score;g.time=200;assert(g.result().score<base);g.time=150;g.repeat=g.cut/2;assert(g.result().score<base);g.repeat=0;g.penalty=600;assert.equal(g.result().score,base-600);g.collisions=100;assert.equal(g.result().score,base-850);const h=new Game('timed');h.cut=h.total/2;assert.equal(h.result().score,5000);});
test('Top five sorted and mode records isolated; independent best stats retained',()=>{let book={};const g=new Game();g.cut=g.total;for(let i=0;i<8;i++){g.time=100+i*10;book=recordRun(book,g.result());}assert.equal(book['garden1:normal'].runs.length,5);assert.equal(book['garden1:normal'].time,100);assert(book['garden1:normal'].runs.every((r,i,a)=>i===0||r.score<=a[i-1].score));const t=new Game('timed');t.time=60;book=recordRun(book,t.result());assert.equal(book['garden1:normal'].runs.length,5);assert.equal(book['garden1:timed'].runs.length,1);});
test('Reset removes boosts, pickup, nest, penalties and switches mode cleanly',()=>{const g=new Game();g.energy.speed=0;g.pickups[0].taken=true;g.nest.revealed=true;g.penalty=600;g.reset('timed');near(g.energy.speed,2.5);assert(!g.pickups[0].taken);assert(!g.nest.revealed);assert.equal(g.penalty,0);assert.equal(g.mode,'timed');});
test('Standard gamepad maps analog steering, triggers, boosts and deadzone',()=>{const p={mapping:'standard',axes:[.1],buttons:Array.from({length:16},()=>({value:0}))};assert.equal(padInput(p).steering,0);p.axes[0]=1;p.buttons[7].value=.7;p.buttons[5].value=1;p.buttons[4].value=1;const i=padInput(p);near(i.steering,1);near(i.throttle,.7);assert(i.speedBoost&&i.turnBoost);assert.deepEqual(padInput(null),{});});
console.log(tests.length+' PASS\n'+tests.join('\n'));

